// PlantDataExpansion.swift
// Seedly
//
// Additional plants for a comprehensive global database.
// Architecture supports future downloadable packs.

import Foundation

extension PlantDatabase {
    
    static let expansionPlants: [Plant] = [
        // MARK: - Vegetables
        Plant(
            id: "zucchini",
            scientificName: "Cucurbita pepo",
            category: .vegetable,
            difficulty: .beginner,
            frostSensitivity: .tender,
            heatTolerance: .high,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 90, betweenRowsCm: 120),
            daysToHarvest: 45...65,
            soilPreferences: [.loamy, .rich, .wellDrained],
            companionPlants: ["corn", "bean", "nasturtium"],
            incompatiblePlants: ["potato"],
            indoorSeedWeeks: 3,
            directSowable: true,
            perennial: false,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 2.5,
            germinationDays: 5...10,
            optimalTempCelsius: 18...30,
            minSoilTempCelsius: 16,
            imageAssetName: "plant_zucchini",
            nameKey: "plant_zucchini",
            descriptionKey: "plant_zucchini_desc"
        ),
        Plant(
            id: "kale",
            scientificName: "Brassica oleracea var. sabellica",
            category: .vegetable,
            difficulty: .beginner,
            frostSensitivity: .hardy,
            heatTolerance: .low,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 45, betweenRowsCm: 60),
            daysToHarvest: 50...70,
            soilPreferences: [.loamy, .rich, .wellDrained],
            companionPlants: ["onion", "garlic", "beet"],
            incompatiblePlants: ["strawberry"],
            indoorSeedWeeks: 5,
            directSowable: true,
            perennial: false,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 1.0,
            germinationDays: 5...10,
            optimalTempCelsius: 10...20,
            minSoilTempCelsius: 5,
            imageAssetName: "plant_kale",
            nameKey: "plant_kale",
            descriptionKey: "plant_kale_desc"
        ),
        Plant(
            id: "garlic",
            scientificName: "Allium sativum",
            category: .vegetable,
            difficulty: .beginner,
            frostSensitivity: .hardy,
            heatTolerance: .moderate,
            waterNeeds: .low,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 15, betweenRowsCm: 30),
            daysToHarvest: 90...240,
            soilPreferences: [.loamy, .wellDrained],
            companionPlants: ["tomato", "pepper", "lettuce"],
            incompatiblePlants: ["bean", "pea"],
            indoorSeedWeeks: nil,
            directSowable: true,
            perennial: false,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .low,
            plantingDepthCm: 5.0,
            germinationDays: 7...14,
            optimalTempCelsius: 5...20,
            minSoilTempCelsius: 0,
            imageAssetName: "plant_garlic",
            nameKey: "plant_garlic",
            descriptionKey: "plant_garlic_desc"
        ),
        Plant(
            id: "peas",
            scientificName: "Pisum sativum",
            category: .vegetable,
            difficulty: .beginner,
            frostSensitivity: .semiHardy,
            heatTolerance: .low,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 8, betweenRowsCm: 60),
            daysToHarvest: 55...70,
            soilPreferences: [.loamy, .wellDrained],
            companionPlants: ["carrot", "radish", "corn"],
            incompatiblePlants: ["onion", "garlic"],
            indoorSeedWeeks: nil,
            directSowable: true,
            perennial: false,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 3.0,
            germinationDays: 7...14,
            optimalTempCelsius: 10...18,
            minSoilTempCelsius: 4,
            imageAssetName: "plant_peas",
            nameKey: "plant_peas",
            descriptionKey: "plant_peas_desc"
        ),
        
        // MARK: - Herbs
        Plant(
            id: "rosemary",
            scientificName: "Salvia rosmarinus",
            category: .herb,
            difficulty: .intermediate,
            frostSensitivity: .semiHardy,
            heatTolerance: .high,
            waterNeeds: .low,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 60, betweenRowsCm: 90),
            daysToHarvest: 80...180,
            soilPreferences: [.sandy, .wellDrained, .chalky],
            companionPlants: ["sage", "thyme", "lavender"],
            incompatiblePlants: [],
            indoorSeedWeeks: 12,
            directSowable: false,
            perennial: true,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .low,
            plantingDepthCm: 0.3,
            germinationDays: 14...21,
            optimalTempCelsius: 15...25,
            minSoilTempCelsius: 10,
            imageAssetName: "plant_rosemary",
            nameKey: "plant_rosemary",
            descriptionKey: "plant_rosemary_desc"
        ),
        Plant(
            id: "thyme",
            scientificName: "Thymus vulgaris",
            category: .herb,
            difficulty: .beginner,
            frostSensitivity: .semiHardy,
            heatTolerance: .high,
            waterNeeds: .low,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 30, betweenRowsCm: 40),
            daysToHarvest: 70...90,
            soilPreferences: [.sandy, .wellDrained],
            companionPlants: ["rosemary", "lavender", "tomato"],
            incompatiblePlants: [],
            indoorSeedWeeks: 8,
            directSowable: true,
            perennial: true,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .low,
            plantingDepthCm: 0.3,
            germinationDays: 14...28,
            optimalTempCelsius: 12...22,
            minSoilTempCelsius: 5,
            imageAssetName: "plant_thyme",
            nameKey: "plant_thyme",
            descriptionKey: "plant_thyme_desc"
        ),
        Plant(
            id: "cilantro",
            scientificName: "Coriandrum sativum",
            category: .herb,
            difficulty: .beginner,
            frostSensitivity: .semiHardy,
            heatTolerance: .low,
            waterNeeds: .moderate,
            sunlight: .partialSun,
            spacing: PlantSpacing(betweenPlantsCm: 15, betweenRowsCm: 30),
            daysToHarvest: 45...70,
            soilPreferences: [.loamy, .wellDrained],
            companionPlants: ["basil", "mint", "dill"],
            incompatiblePlants: ["fennel"],
            indoorSeedWeeks: nil,
            directSowable: true,
            perennial: false,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 1.0,
            germinationDays: 7...14,
            optimalTempCelsius: 10...25,
            minSoilTempCelsius: 5,
            imageAssetName: "plant_cilantro",
            nameKey: "plant_cilantro",
            descriptionKey: "plant_cilantro_desc"
        ),
        
        // MARK: - Fruits
        Plant(
            id: "blueberry",
            scientificName: "Vaccinium corymbosum",
            category: .berry,
            difficulty: .intermediate,
            frostSensitivity: .hardy,
            heatTolerance: .moderate,
            waterNeeds: .high,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 150, betweenRowsCm: 250),
            daysToHarvest: 120...180,
            soilPreferences: [.peat, .wellDrained],
            companionPlants: ["strawberry", "cranberry"],
            incompatiblePlants: [],
            indoorSeedWeeks: nil,
            directSowable: false,
            perennial: true,
            containerFriendly: true,
            greenhouseSuitable: false,
            humidityPreference: .moderate,
            plantingDepthCm: 0,
            germinationDays: 30...90,
            optimalTempCelsius: 15...25,
            minSoilTempCelsius: 5,
            imageAssetName: "plant_blueberry",
            nameKey: "plant_blueberry",
            descriptionKey: "plant_blueberry_desc"
        ),
        Plant(
            id: "raspberry",
            scientificName: "Rubus idaeus",
            category: .berry,
            difficulty: .intermediate,
            frostSensitivity: .hardy,
            heatTolerance: .moderate,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 60, betweenRowsCm: 200),
            daysToHarvest: 120...150,
            soilPreferences: [.loamy, .wellDrained, .rich],
            companionPlants: ["garlic", "tansy"],
            incompatiblePlants: ["blackberry"],
            indoorSeedWeeks: nil,
            directSowable: false,
            perennial: true,
            containerFriendly: false,
            greenhouseSuitable: false,
            humidityPreference: .moderate,
            plantingDepthCm: 0,
            germinationDays: 0...0,
            optimalTempCelsius: 15...25,
            minSoilTempCelsius: 5,
            imageAssetName: "plant_raspberry",
            nameKey: "plant_raspberry",
            descriptionKey: "plant_raspberry_desc"
        ),
        
        // MARK: - Flowers
        Plant(
            id: "marigold",
            scientificName: "Tagetes",
            category: .flower,
            difficulty: .beginner,
            frostSensitivity: .tender,
            heatTolerance: .high,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 25, betweenRowsCm: 30),
            daysToHarvest: 45...50,
            soilPreferences: [.loamy, .wellDrained],
            companionPlants: ["tomato", "pepper", "bean"],
            incompatiblePlants: [],
            indoorSeedWeeks: 6,
            directSowable: true,
            perennial: false,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 0.6,
            germinationDays: 5...7,
            optimalTempCelsius: 18...30,
            minSoilTempCelsius: 10,
            imageAssetName: "plant_marigold",
            nameKey: "plant_marigold",
            descriptionKey: "plant_marigold_desc"
        ),
        
        // MARK: - Tropical
        Plant(
            id: "mango",
            scientificName: "Mangifera indica",
            category: .tropical,
            difficulty: .advanced,
            frostSensitivity: .tropical,
            heatTolerance: .extreme,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 800, betweenRowsCm: 800),
            daysToHarvest: 100...150,
            soilPreferences: [.loamy, .wellDrained, .sandy],
            companionPlants: [],
            incompatiblePlants: [],
            indoorSeedWeeks: nil,
            directSowable: true,
            perennial: true,
            containerFriendly: false,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 2.0,
            germinationDays: 14...21,
            optimalTempCelsius: 24...35,
            minSoilTempCelsius: 20,
            imageAssetName: "plant_mango",
            nameKey: "plant_mango",
            descriptionKey: "plant_mango_desc"
        ),
        Plant(
            id: "banana",
            scientificName: "Musa acuminata",
            category: .tropical,
            difficulty: .intermediate,
            frostSensitivity: .tropical,
            heatTolerance: .high,
            waterNeeds: .veryHigh,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 300, betweenRowsCm: 400),
            daysToHarvest: 270...365,
            soilPreferences: [.loamy, .rich, .wellDrained],
            companionPlants: [],
            incompatiblePlants: [],
            indoorSeedWeeks: nil,
            directSowable: false,
            perennial: true,
            containerFriendly: false,
            greenhouseSuitable: true,
            humidityPreference: .veryHigh,
            plantingDepthCm: 0,
            germinationDays: 0...0,
            optimalTempCelsius: 26...35,
            minSoilTempCelsius: 22,
            imageAssetName: "plant_banana",
            nameKey: "plant_banana",
            descriptionKey: "plant_banana_desc"
        ),
    ]
}
