// PlantDatabaseFull.swift
// Seedly
//
// Comprehensive plant database with 60+ additional plants across all categories.

import Foundation

extension PlantDatabase {
    
    static let fullPlantList: [Plant] = [
        // ═══════════════════════════════════════
        // MARK: - VEGETABLES (25+)
        // ═══════════════════════════════════════
        
        Plant(
            id: "potato",
            scientificName: "Solanum tuberosum",
            category: .vegetable,
            difficulty: .beginner,
            frostSensitivity: .semiHardy,
            heatTolerance: .moderate,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 30, betweenRowsCm: 75),
            daysToHarvest: 70...120,
            soilPreferences: [.loamy, .sandy, .wellDrained],
            companionPlants: ["bean", "corn", "cabbage"],
            incompatiblePlants: ["tomato", "cucumber", "sunflower"],
            indoorSeedWeeks: nil,
            directSowable: true,
            perennial: false,
            containerFriendly: true,
            greenhouseSuitable: false,
            humidityPreference: .moderate,
            plantingDepthCm: 10.0,
            germinationDays: 14...21,
            optimalTempCelsius: 15...22,
            minSoilTempCelsius: 7,
            imageAssetName: "plant_potato",
            nameKey: "plant_potato",
            descriptionKey: "plant_potato_desc"
        ),
        Plant(
            id: "sweetPotato",
            scientificName: "Ipomoea batatas",
            category: .vegetable,
            difficulty: .intermediate,
            frostSensitivity: .tender,
            heatTolerance: .high,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 30, betweenRowsCm: 90),
            daysToHarvest: 90...170,
            soilPreferences: [.sandy, .loamy, .wellDrained],
            companionPlants: ["bean", "corn"],
            incompatiblePlants: ["squash"],
            indoorSeedWeeks: nil,
            directSowable: true,
            perennial: false,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 5.0,
            germinationDays: 7...14,
            optimalTempCelsius: 21...35,
            minSoilTempCelsius: 18,
            imageAssetName: "plant_sweetPotato",
            nameKey: "plant_sweetPotato",
            descriptionKey: "plant_sweetPotato_desc"
        ),
        Plant(
            id: "corn",
            scientificName: "Zea mays",
            category: .vegetable,
            difficulty: .intermediate,
            frostSensitivity: .tender,
            heatTolerance: .high,
            waterNeeds: .high,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 25, betweenRowsCm: 75),
            daysToHarvest: 60...100,
            soilPreferences: [.loamy, .rich, .wellDrained],
            companionPlants: ["bean", "squash", "cucumber"],
            incompatiblePlants: ["tomato"],
            indoorSeedWeeks: nil,
            directSowable: true,
            perennial: false,
            containerFriendly: false,
            greenhouseSuitable: false,
            humidityPreference: .moderate,
            plantingDepthCm: 5.0,
            germinationDays: 7...14,
            optimalTempCelsius: 18...32,
            minSoilTempCelsius: 16,
            imageAssetName: "plant_corn",
            nameKey: "plant_corn",
            descriptionKey: "plant_corn_desc"
        ),
        Plant(
            id: "bean",
            scientificName: "Phaseolus vulgaris",
            category: .vegetable,
            difficulty: .beginner,
            frostSensitivity: .tender,
            heatTolerance: .moderate,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 10, betweenRowsCm: 45),
            daysToHarvest: 50...65,
            soilPreferences: [.loamy, .wellDrained],
            companionPlants: ["corn", "squash", "carrot"],
            incompatiblePlants: ["onion", "garlic", "fennel"],
            indoorSeedWeeks: nil,
            directSowable: true,
            perennial: false,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 4.0,
            germinationDays: 7...14,
            optimalTempCelsius: 16...30,
            minSoilTempCelsius: 12,
            imageAssetName: "plant_bean",
            nameKey: "plant_bean",
            descriptionKey: "plant_bean_desc"
        ),
        Plant(
            id: "broccoli",
            scientificName: "Brassica oleracea var. italica",
            category: .vegetable,
            difficulty: .intermediate,
            frostSensitivity: .semiHardy,
            heatTolerance: .low,
            waterNeeds: .high,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 45, betweenRowsCm: 60),
            daysToHarvest: 60...100,
            soilPreferences: [.loamy, .rich, .wellDrained],
            companionPlants: ["onion", "garlic", "celery"],
            incompatiblePlants: ["strawberry", "tomato"],
            indoorSeedWeeks: 6,
            directSowable: true,
            perennial: false,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 1.0,
            germinationDays: 5...10,
            optimalTempCelsius: 7...24,
            minSoilTempCelsius: 5,
            imageAssetName: "plant_broccoli",
            nameKey: "plant_broccoli",
            descriptionKey: "plant_broccoli_desc"
        ),
        Plant(
            id: "cauliflower",
            scientificName: "Brassica oleracea var. botrytis",
            category: .vegetable,
            difficulty: .advanced,
            frostSensitivity: .semiHardy,
            heatTolerance: .low,
            waterNeeds: .high,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 60, betweenRowsCm: 75),
            daysToHarvest: 55...100,
            soilPreferences: [.loamy, .rich, .moistRetentive],
            companionPlants: ["celery", "onion", "garlic"],
            incompatiblePlants: ["strawberry", "tomato"],
            indoorSeedWeeks: 6,
            directSowable: false,
            perennial: false,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .high,
            plantingDepthCm: 1.0,
            germinationDays: 5...10,
            optimalTempCelsius: 15...20,
            minSoilTempCelsius: 5,
            imageAssetName: "plant_cauliflower",
            nameKey: "plant_cauliflower",
            descriptionKey: "plant_cauliflower_desc"
        ),
        Plant(
            id: "cabbage",
            scientificName: "Brassica oleracea var. capitata",
            category: .vegetable,
            difficulty: .intermediate,
            frostSensitivity: .hardy,
            heatTolerance: .low,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 45, betweenRowsCm: 60),
            daysToHarvest: 70...120,
            soilPreferences: [.loamy, .rich, .moistRetentive],
            companionPlants: ["onion", "celery", "dill"],
            incompatiblePlants: ["strawberry", "tomato"],
            indoorSeedWeeks: 6,
            directSowable: true,
            perennial: false,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 1.0,
            germinationDays: 5...10,
            optimalTempCelsius: 7...24,
            minSoilTempCelsius: 4,
            imageAssetName: "plant_cabbage",
            nameKey: "plant_cabbage",
            descriptionKey: "plant_cabbage_desc"
        ),
        Plant(
            id: "eggplant",
            scientificName: "Solanum melongena",
            category: .vegetable,
            difficulty: .intermediate,
            frostSensitivity: .tender,
            heatTolerance: .high,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 60, betweenRowsCm: 75),
            daysToHarvest: 65...80,
            soilPreferences: [.loamy, .rich, .wellDrained],
            companionPlants: ["pepper", "tomato", "basil"],
            incompatiblePlants: ["fennel"],
            indoorSeedWeeks: 8,
            directSowable: false,
            perennial: false,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 0.6,
            germinationDays: 7...14,
            optimalTempCelsius: 22...32,
            minSoilTempCelsius: 21,
            imageAssetName: "plant_eggplant",
            nameKey: "plant_eggplant",
            descriptionKey: "plant_eggplant_desc"
        ),
        Plant(
            id: "radish",
            scientificName: "Raphanus sativus",
            category: .vegetable,
            difficulty: .beginner,
            frostSensitivity: .semiHardy,
            heatTolerance: .low,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 5, betweenRowsCm: 25),
            daysToHarvest: 20...30,
            soilPreferences: [.sandy, .loamy, .wellDrained],
            companionPlants: ["carrot", "lettuce", "peas"],
            incompatiblePlants: [],
            indoorSeedWeeks: nil,
            directSowable: true,
            perennial: false,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 1.5,
            germinationDays: 3...7,
            optimalTempCelsius: 10...18,
            minSoilTempCelsius: 4,
            imageAssetName: "plant_radish",
            nameKey: "plant_radish",
            descriptionKey: "plant_radish_desc"
        ),
        Plant(
            id: "beetroot",
            scientificName: "Beta vulgaris",
            category: .vegetable,
            difficulty: .beginner,
            frostSensitivity: .semiHardy,
            heatTolerance: .moderate,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 10, betweenRowsCm: 30),
            daysToHarvest: 55...70,
            soilPreferences: [.loamy, .sandy, .wellDrained],
            companionPlants: ["onion", "lettuce", "cabbage"],
            incompatiblePlants: ["bean"],
            indoorSeedWeeks: nil,
            directSowable: true,
            perennial: false,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 2.0,
            germinationDays: 7...14,
            optimalTempCelsius: 10...24,
            minSoilTempCelsius: 7,
            imageAssetName: "plant_beetroot",
            nameKey: "plant_beetroot",
            descriptionKey: "plant_beetroot_desc"
        ),
        Plant(
            id: "celery",
            scientificName: "Apium graveolens",
            category: .vegetable,
            difficulty: .advanced,
            frostSensitivity: .semiHardy,
            heatTolerance: .low,
            waterNeeds: .veryHigh,
            sunlight: .partialSun,
            spacing: PlantSpacing(betweenPlantsCm: 25, betweenRowsCm: 45),
            daysToHarvest: 85...120,
            soilPreferences: [.rich, .moistRetentive, .loamy],
            companionPlants: ["tomato", "cabbage", "bean"],
            incompatiblePlants: ["parsnip", "potato"],
            indoorSeedWeeks: 10,
            directSowable: false,
            perennial: false,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .veryHigh,
            plantingDepthCm: 0.1,
            germinationDays: 14...21,
            optimalTempCelsius: 15...21,
            minSoilTempCelsius: 10,
            imageAssetName: "plant_celery",
            nameKey: "plant_celery",
            descriptionKey: "plant_celery_desc"
        ),
        Plant(
            id: "pumpkin",
            scientificName: "Cucurbita maxima",
            category: .vegetable,
            difficulty: .intermediate,
            frostSensitivity: .tender,
            heatTolerance: .high,
            waterNeeds: .high,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 150, betweenRowsCm: 200),
            daysToHarvest: 90...120,
            soilPreferences: [.loamy, .rich, .wellDrained],
            companionPlants: ["corn", "bean"],
            incompatiblePlants: ["potato"],
            indoorSeedWeeks: 3,
            directSowable: true,
            perennial: false,
            containerFriendly: false,
            greenhouseSuitable: false,
            humidityPreference: .moderate,
            plantingDepthCm: 3.0,
            germinationDays: 5...10,
            optimalTempCelsius: 20...30,
            minSoilTempCelsius: 16,
            imageAssetName: "plant_pumpkin",
            nameKey: "plant_pumpkin",
            descriptionKey: "plant_pumpkin_desc"
        ),
        Plant(
            id: "squash",
            scientificName: "Cucurbita moschata",
            category: .vegetable,
            difficulty: .beginner,
            frostSensitivity: .tender,
            heatTolerance: .high,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 90, betweenRowsCm: 150),
            daysToHarvest: 85...110,
            soilPreferences: [.loamy, .rich, .wellDrained],
            companionPlants: ["corn", "bean", "nasturtium"],
            incompatiblePlants: ["potato"],
            indoorSeedWeeks: 3,
            directSowable: true,
            perennial: false,
            containerFriendly: false,
            greenhouseSuitable: false,
            humidityPreference: .moderate,
            plantingDepthCm: 2.5,
            germinationDays: 5...10,
            optimalTempCelsius: 18...30,
            minSoilTempCelsius: 16,
            imageAssetName: "plant_squash",
            nameKey: "plant_squash",
            descriptionKey: "plant_squash_desc"
        ),
        Plant(
            id: "brusselsSprouts",
            scientificName: "Brassica oleracea var. gemmifera",
            category: .vegetable,
            difficulty: .advanced,
            frostSensitivity: .hardy,
            heatTolerance: .low,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 60, betweenRowsCm: 75),
            daysToHarvest: 90...180,
            soilPreferences: [.loamy, .rich, .wellDrained],
            companionPlants: ["onion", "garlic", "celery"],
            incompatiblePlants: ["strawberry"],
            indoorSeedWeeks: 6,
            directSowable: false,
            perennial: false,
            containerFriendly: false,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 1.0,
            germinationDays: 5...10,
            optimalTempCelsius: 7...24,
            minSoilTempCelsius: 5,
            imageAssetName: "plant_brusselsSprouts",
            nameKey: "plant_brusselsSprouts",
            descriptionKey: "plant_brusselsSprouts_desc"
        ),
        Plant(
            id: "leek",
            scientificName: "Allium ampeloprasum",
            category: .vegetable,
            difficulty: .intermediate,
            frostSensitivity: .hardy,
            heatTolerance: .low,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 15, betweenRowsCm: 30),
            daysToHarvest: 100...150,
            soilPreferences: [.loamy, .rich, .moistRetentive],
            companionPlants: ["carrot", "celery", "onion"],
            incompatiblePlants: ["bean", "pea"],
            indoorSeedWeeks: 10,
            directSowable: false,
            perennial: false,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 1.0,
            germinationDays: 10...14,
            optimalTempCelsius: 10...22,
            minSoilTempCelsius: 7,
            imageAssetName: "plant_leek",
            nameKey: "plant_leek",
            descriptionKey: "plant_leek_desc"
        ),
        Plant(
            id: "asparagus",
            scientificName: "Asparagus officinalis",
            category: .vegetable,
            difficulty: .advanced,
            frostSensitivity: .hardy,
            heatTolerance: .moderate,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 45, betweenRowsCm: 120),
            daysToHarvest: 730...1095,
            soilPreferences: [.sandy, .loamy, .wellDrained],
            companionPlants: ["tomato", "parsley", "basil"],
            incompatiblePlants: ["garlic", "onion"],
            indoorSeedWeeks: nil,
            directSowable: false,
            perennial: true,
            containerFriendly: false,
            greenhouseSuitable: false,
            humidityPreference: .moderate,
            plantingDepthCm: 15.0,
            germinationDays: 14...28,
            optimalTempCelsius: 15...24,
            minSoilTempCelsius: 10,
            imageAssetName: "plant_asparagus",
            nameKey: "plant_asparagus",
            descriptionKey: "plant_asparagus_desc"
        ),
        Plant(
            id: "swissChard",
            scientificName: "Beta vulgaris subsp. vulgaris",
            category: .vegetable,
            difficulty: .beginner,
            frostSensitivity: .semiHardy,
            heatTolerance: .moderate,
            waterNeeds: .moderate,
            sunlight: .partialSun,
            spacing: PlantSpacing(betweenPlantsCm: 20, betweenRowsCm: 45),
            daysToHarvest: 50...60,
            soilPreferences: [.loamy, .rich, .wellDrained],
            companionPlants: ["bean", "cabbage", "onion"],
            incompatiblePlants: [],
            indoorSeedWeeks: 4,
            directSowable: true,
            perennial: false,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 2.5,
            germinationDays: 7...14,
            optimalTempCelsius: 10...24,
            minSoilTempCelsius: 5,
            imageAssetName: "plant_swissChard",
            nameKey: "plant_swissChard",
            descriptionKey: "plant_swissChard_desc"
        ),
        Plant(
            id: "turnip",
            scientificName: "Brassica rapa",
            category: .vegetable,
            difficulty: .beginner,
            frostSensitivity: .hardy,
            heatTolerance: .low,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 10, betweenRowsCm: 30),
            daysToHarvest: 40...60,
            soilPreferences: [.loamy, .sandy, .wellDrained],
            companionPlants: ["peas", "onion"],
            incompatiblePlants: ["potato"],
            indoorSeedWeeks: nil,
            directSowable: true,
            perennial: false,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 1.0,
            germinationDays: 5...10,
            optimalTempCelsius: 10...18,
            minSoilTempCelsius: 4,
            imageAssetName: "plant_turnip",
            nameKey: "plant_turnip",
            descriptionKey: "plant_turnip_desc"
        ),
        Plant(
            id: "parsnip",
            scientificName: "Pastinaca sativa",
            category: .vegetable,
            difficulty: .intermediate,
            frostSensitivity: .hardy,
            heatTolerance: .low,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 10, betweenRowsCm: 30),
            daysToHarvest: 100...130,
            soilPreferences: [.sandy, .loamy, .wellDrained],
            companionPlants: ["onion", "garlic", "radish"],
            incompatiblePlants: ["carrot", "celery"],
            indoorSeedWeeks: nil,
            directSowable: true,
            perennial: false,
            containerFriendly: false,
            greenhouseSuitable: false,
            humidityPreference: .moderate,
            plantingDepthCm: 1.5,
            germinationDays: 14...28,
            optimalTempCelsius: 10...18,
            minSoilTempCelsius: 2,
            imageAssetName: "plant_parsnip",
            nameKey: "plant_parsnip",
            descriptionKey: "plant_parsnip_desc"
        ),
        Plant(
            id: "okra",
            scientificName: "Abelmoschus esculentus",
            category: .vegetable,
            difficulty: .intermediate,
            frostSensitivity: .tender,
            heatTolerance: .extreme,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 45, betweenRowsCm: 90),
            daysToHarvest: 50...65,
            soilPreferences: [.loamy, .sandy, .wellDrained],
            companionPlants: ["pepper", "eggplant", "melon"],
            incompatiblePlants: [],
            indoorSeedWeeks: 4,
            directSowable: true,
            perennial: false,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 2.0,
            germinationDays: 7...14,
            optimalTempCelsius: 24...35,
            minSoilTempCelsius: 18,
            imageAssetName: "plant_okra",
            nameKey: "plant_okra",
            descriptionKey: "plant_okra_desc"
        ),
        
        // ═══════════════════════════════════════
        // MARK: - HERBS (10+)
        // ═══════════════════════════════════════
        
        Plant(
            id: "parsley",
            scientificName: "Petroselinum crispum",
            category: .herb,
            difficulty: .beginner,
            frostSensitivity: .semiHardy,
            heatTolerance: .moderate,
            waterNeeds: .moderate,
            sunlight: .partialSun,
            spacing: PlantSpacing(betweenPlantsCm: 20, betweenRowsCm: 30),
            daysToHarvest: 70...90,
            soilPreferences: [.loamy, .rich, .wellDrained],
            companionPlants: ["tomato", "asparagus", "carrot"],
            incompatiblePlants: ["mint"],
            indoorSeedWeeks: 8,
            directSowable: true,
            perennial: false,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 0.5,
            germinationDays: 14...28,
            optimalTempCelsius: 10...25,
            minSoilTempCelsius: 5,
            imageAssetName: "plant_parsley",
            nameKey: "plant_parsley",
            descriptionKey: "plant_parsley_desc"
        ),
        Plant(
            id: "dill",
            scientificName: "Anethum graveolens",
            category: .herb,
            difficulty: .beginner,
            frostSensitivity: .semiHardy,
            heatTolerance: .moderate,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 25, betweenRowsCm: 30),
            daysToHarvest: 40...60,
            soilPreferences: [.sandy, .loamy, .wellDrained],
            companionPlants: ["cabbage", "lettuce", "cucumber"],
            incompatiblePlants: ["carrot", "fennel"],
            indoorSeedWeeks: nil,
            directSowable: true,
            perennial: false,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .low,
            plantingDepthCm: 0.5,
            germinationDays: 10...14,
            optimalTempCelsius: 15...25,
            minSoilTempCelsius: 8,
            imageAssetName: "plant_dill",
            nameKey: "plant_dill",
            descriptionKey: "plant_dill_desc"
        ),
        Plant(
            id: "sage",
            scientificName: "Salvia officinalis",
            category: .herb,
            difficulty: .beginner,
            frostSensitivity: .semiHardy,
            heatTolerance: .high,
            waterNeeds: .low,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 60, betweenRowsCm: 60),
            daysToHarvest: 75...90,
            soilPreferences: [.sandy, .wellDrained, .chalky],
            companionPlants: ["rosemary", "thyme", "cabbage"],
            incompatiblePlants: ["basil", "cucumber"],
            indoorSeedWeeks: 6,
            directSowable: true,
            perennial: true,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .low,
            plantingDepthCm: 0.3,
            germinationDays: 14...21,
            optimalTempCelsius: 15...25,
            minSoilTempCelsius: 10,
            imageAssetName: "plant_sage",
            nameKey: "plant_sage",
            descriptionKey: "plant_sage_desc"
        ),
        Plant(
            id: "oregano",
            scientificName: "Origanum vulgare",
            category: .herb,
            difficulty: .beginner,
            frostSensitivity: .semiHardy,
            heatTolerance: .high,
            waterNeeds: .low,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 30, betweenRowsCm: 45),
            daysToHarvest: 70...90,
            soilPreferences: [.sandy, .loamy, .wellDrained],
            companionPlants: ["pepper", "tomato", "basil"],
            incompatiblePlants: [],
            indoorSeedWeeks: 8,
            directSowable: true,
            perennial: true,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .low,
            plantingDepthCm: 0.1,
            germinationDays: 7...14,
            optimalTempCelsius: 15...30,
            minSoilTempCelsius: 10,
            imageAssetName: "plant_oregano",
            nameKey: "plant_oregano",
            descriptionKey: "plant_oregano_desc"
        ),
        Plant(
            id: "chives",
            scientificName: "Allium schoenoprasum",
            category: .herb,
            difficulty: .beginner,
            frostSensitivity: .hardy,
            heatTolerance: .moderate,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 15, betweenRowsCm: 30),
            daysToHarvest: 60...90,
            soilPreferences: [.loamy, .rich, .wellDrained],
            companionPlants: ["carrot", "tomato", "rose"],
            incompatiblePlants: ["bean", "pea"],
            indoorSeedWeeks: 8,
            directSowable: true,
            perennial: true,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 0.5,
            germinationDays: 10...14,
            optimalTempCelsius: 10...25,
            minSoilTempCelsius: 5,
            imageAssetName: "plant_chives",
            nameKey: "plant_chives",
            descriptionKey: "plant_chives_desc"
        ),
        Plant(
            id: "lemonBalm",
            scientificName: "Melissa officinalis",
            category: .herb,
            difficulty: .beginner,
            frostSensitivity: .hardy,
            heatTolerance: .moderate,
            waterNeeds: .moderate,
            sunlight: .partialSun,
            spacing: PlantSpacing(betweenPlantsCm: 45, betweenRowsCm: 60),
            daysToHarvest: 70...90,
            soilPreferences: [.loamy, .wellDrained],
            companionPlants: ["tomato", "squash"],
            incompatiblePlants: [],
            indoorSeedWeeks: 6,
            directSowable: true,
            perennial: true,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 0.1,
            germinationDays: 10...14,
            optimalTempCelsius: 12...22,
            minSoilTempCelsius: 10,
            imageAssetName: "plant_lemonBalm",
            nameKey: "plant_lemonBalm",
            descriptionKey: "plant_lemonBalm_desc"
        ),
        
        // ═══════════════════════════════════════
        // MARK: - FLOWERS (10+)
        // ═══════════════════════════════════════
        
        Plant(
            id: "rose",
            scientificName: "Rosa",
            category: .flower,
            difficulty: .intermediate,
            frostSensitivity: .semiHardy,
            heatTolerance: .moderate,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 60, betweenRowsCm: 90),
            daysToHarvest: 60...90,
            soilPreferences: [.loamy, .rich, .wellDrained],
            companionPlants: ["lavender", "garlic", "chives"],
            incompatiblePlants: [],
            indoorSeedWeeks: nil,
            directSowable: false,
            perennial: true,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 0,
            germinationDays: 14...60,
            optimalTempCelsius: 15...25,
            minSoilTempCelsius: 5,
            imageAssetName: "plant_rose",
            nameKey: "plant_rose",
            descriptionKey: "plant_rose_desc"
        ),
        Plant(
            id: "dahlia",
            scientificName: "Dahlia pinnata",
            category: .flower,
            difficulty: .intermediate,
            frostSensitivity: .tender,
            heatTolerance: .moderate,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 60, betweenRowsCm: 90),
            daysToHarvest: 90...120,
            soilPreferences: [.loamy, .rich, .wellDrained],
            companionPlants: ["zinnia", "cosmos"],
            incompatiblePlants: [],
            indoorSeedWeeks: 6,
            directSowable: false,
            perennial: true,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 10.0,
            germinationDays: 7...14,
            optimalTempCelsius: 15...25,
            minSoilTempCelsius: 15,
            imageAssetName: "plant_dahlia",
            nameKey: "plant_dahlia",
            descriptionKey: "plant_dahlia_desc"
        ),
        Plant(
            id: "tulip",
            scientificName: "Tulipa",
            category: .flower,
            difficulty: .beginner,
            frostSensitivity: .hardy,
            heatTolerance: .low,
            waterNeeds: .low,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 10, betweenRowsCm: 25),
            daysToHarvest: 120...180,
            soilPreferences: [.sandy, .loamy, .wellDrained],
            companionPlants: ["daffodil", "grape hyacinth"],
            incompatiblePlants: [],
            indoorSeedWeeks: nil,
            directSowable: true,
            perennial: true,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .low,
            plantingDepthCm: 15.0,
            germinationDays: 14...28,
            optimalTempCelsius: 5...18,
            minSoilTempCelsius: 0,
            imageAssetName: "plant_tulip",
            nameKey: "plant_tulip",
            descriptionKey: "plant_tulip_desc"
        ),
        Plant(
            id: "zinnia",
            scientificName: "Zinnia elegans",
            category: .flower,
            difficulty: .beginner,
            frostSensitivity: .tender,
            heatTolerance: .high,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 20, betweenRowsCm: 30),
            daysToHarvest: 60...70,
            soilPreferences: [.loamy, .wellDrained],
            companionPlants: ["dahlia", "cosmos", "tomato"],
            incompatiblePlants: [],
            indoorSeedWeeks: 4,
            directSowable: true,
            perennial: false,
            containerFriendly: true,
            greenhouseSuitable: false,
            humidityPreference: .low,
            plantingDepthCm: 0.6,
            germinationDays: 5...7,
            optimalTempCelsius: 20...30,
            minSoilTempCelsius: 15,
            imageAssetName: "plant_zinnia",
            nameKey: "plant_zinnia",
            descriptionKey: "plant_zinnia_desc"
        ),
        Plant(
            id: "cosmos",
            scientificName: "Cosmos bipinnatus",
            category: .flower,
            difficulty: .beginner,
            frostSensitivity: .tender,
            heatTolerance: .high,
            waterNeeds: .low,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 30, betweenRowsCm: 45),
            daysToHarvest: 60...90,
            soilPreferences: [.sandy, .loamy, .wellDrained],
            companionPlants: ["zinnia", "tomato", "pepper"],
            incompatiblePlants: [],
            indoorSeedWeeks: nil,
            directSowable: true,
            perennial: false,
            containerFriendly: true,
            greenhouseSuitable: false,
            humidityPreference: .low,
            plantingDepthCm: 0.3,
            germinationDays: 7...10,
            optimalTempCelsius: 18...30,
            minSoilTempCelsius: 15,
            imageAssetName: "plant_cosmos",
            nameKey: "plant_cosmos",
            descriptionKey: "plant_cosmos_desc"
        ),
        Plant(
            id: "nasturtium",
            scientificName: "Tropaeolum majus",
            category: .flower,
            difficulty: .beginner,
            frostSensitivity: .tender,
            heatTolerance: .moderate,
            waterNeeds: .low,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 25, betweenRowsCm: 30),
            daysToHarvest: 45...60,
            soilPreferences: [.sandy, .wellDrained],
            companionPlants: ["tomato", "cabbage", "cucumber"],
            incompatiblePlants: [],
            indoorSeedWeeks: nil,
            directSowable: true,
            perennial: false,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .low,
            plantingDepthCm: 1.5,
            germinationDays: 7...14,
            optimalTempCelsius: 15...25,
            minSoilTempCelsius: 10,
            imageAssetName: "plant_nasturtium",
            nameKey: "plant_nasturtium",
            descriptionKey: "plant_nasturtium_desc"
        ),
        Plant(
            id: "petunia",
            scientificName: "Petunia × atkinsiana",
            category: .flower,
            difficulty: .beginner,
            frostSensitivity: .tender,
            heatTolerance: .high,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 25, betweenRowsCm: 30),
            daysToHarvest: 60...75,
            soilPreferences: [.loamy, .wellDrained],
            companionPlants: ["tomato", "basil"],
            incompatiblePlants: [],
            indoorSeedWeeks: 10,
            directSowable: false,
            perennial: false,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 0.1,
            germinationDays: 7...14,
            optimalTempCelsius: 18...28,
            minSoilTempCelsius: 15,
            imageAssetName: "plant_petunia",
            nameKey: "plant_petunia",
            descriptionKey: "plant_petunia_desc"
        ),
        
        // ═══════════════════════════════════════
        // MARK: - FRUITS & BERRIES (8+)
        // ═══════════════════════════════════════
        
        Plant(
            id: "grape",
            scientificName: "Vitis vinifera",
            category: .fruit,
            difficulty: .advanced,
            frostSensitivity: .semiHardy,
            heatTolerance: .high,
            waterNeeds: .low,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 200, betweenRowsCm: 300),
            daysToHarvest: 150...180,
            soilPreferences: [.sandy, .loamy, .wellDrained],
            companionPlants: ["rose", "garlic"],
            incompatiblePlants: [],
            indoorSeedWeeks: nil,
            directSowable: false,
            perennial: true,
            containerFriendly: false,
            greenhouseSuitable: true,
            humidityPreference: .low,
            plantingDepthCm: 0,
            germinationDays: 0...0,
            optimalTempCelsius: 15...30,
            minSoilTempCelsius: 10,
            imageAssetName: "plant_grape",
            nameKey: "plant_grape",
            descriptionKey: "plant_grape_desc"
        ),
        Plant(
            id: "watermelon",
            scientificName: "Citrullus lanatus",
            category: .fruit,
            difficulty: .intermediate,
            frostSensitivity: .tender,
            heatTolerance: .extreme,
            waterNeeds: .high,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 90, betweenRowsCm: 200),
            daysToHarvest: 70...90,
            soilPreferences: [.sandy, .loamy, .wellDrained],
            companionPlants: ["corn", "sunflower"],
            incompatiblePlants: ["potato"],
            indoorSeedWeeks: 3,
            directSowable: true,
            perennial: false,
            containerFriendly: false,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 2.5,
            germinationDays: 5...10,
            optimalTempCelsius: 22...35,
            minSoilTempCelsius: 21,
            imageAssetName: "plant_watermelon",
            nameKey: "plant_watermelon",
            descriptionKey: "plant_watermelon_desc"
        ),
        Plant(
            id: "melon",
            scientificName: "Cucumis melo",
            category: .fruit,
            difficulty: .intermediate,
            frostSensitivity: .tender,
            heatTolerance: .high,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 60, betweenRowsCm: 150),
            daysToHarvest: 75...95,
            soilPreferences: [.sandy, .loamy, .wellDrained],
            companionPlants: ["corn", "sunflower"],
            incompatiblePlants: ["potato", "cucumber"],
            indoorSeedWeeks: 3,
            directSowable: true,
            perennial: false,
            containerFriendly: false,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 2.5,
            germinationDays: 5...10,
            optimalTempCelsius: 20...30,
            minSoilTempCelsius: 18,
            imageAssetName: "plant_melon",
            nameKey: "plant_melon",
            descriptionKey: "plant_melon_desc"
        ),
        Plant(
            id: "blackberry",
            scientificName: "Rubus fruticosus",
            category: .berry,
            difficulty: .beginner,
            frostSensitivity: .hardy,
            heatTolerance: .moderate,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 90, betweenRowsCm: 250),
            daysToHarvest: 120...150,
            soilPreferences: [.loamy, .wellDrained, .rich],
            companionPlants: ["tansy", "mint"],
            incompatiblePlants: ["raspberry"],
            indoorSeedWeeks: nil,
            directSowable: false,
            perennial: true,
            containerFriendly: false,
            greenhouseSuitable: false,
            humidityPreference: .moderate,
            plantingDepthCm: 0,
            germinationDays: 0...0,
            optimalTempCelsius: 15...25,
            minSoilTempCelsius: 5,
            imageAssetName: "plant_blackberry",
            nameKey: "plant_blackberry",
            descriptionKey: "plant_blackberry_desc"
        ),
        Plant(
            id: "gooseberry",
            scientificName: "Ribes uva-crispa",
            category: .berry,
            difficulty: .beginner,
            frostSensitivity: .hardy,
            heatTolerance: .low,
            waterNeeds: .moderate,
            sunlight: .partialSun,
            spacing: PlantSpacing(betweenPlantsCm: 120, betweenRowsCm: 150),
            daysToHarvest: 120...150,
            soilPreferences: [.loamy, .rich, .wellDrained],
            companionPlants: ["tomato", "tansy"],
            incompatiblePlants: [],
            indoorSeedWeeks: nil,
            directSowable: false,
            perennial: true,
            containerFriendly: true,
            greenhouseSuitable: false,
            humidityPreference: .moderate,
            plantingDepthCm: 0,
            germinationDays: 0...0,
            optimalTempCelsius: 10...22,
            minSoilTempCelsius: 0,
            imageAssetName: "plant_gooseberry",
            nameKey: "plant_gooseberry",
            descriptionKey: "plant_gooseberry_desc"
        ),
        
        // ═══════════════════════════════════════
        // MARK: - TROPICAL (5+)
        // ═══════════════════════════════════════
        
        Plant(
            id: "avocado",
            scientificName: "Persea americana",
            category: .tropical,
            difficulty: .advanced,
            frostSensitivity: .tropical,
            heatTolerance: .high,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 600, betweenRowsCm: 600),
            daysToHarvest: 365...1825,
            soilPreferences: [.loamy, .wellDrained],
            companionPlants: [],
            incompatiblePlants: [],
            indoorSeedWeeks: nil,
            directSowable: true,
            perennial: true,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 2.5,
            germinationDays: 14...60,
            optimalTempCelsius: 20...30,
            minSoilTempCelsius: 18,
            imageAssetName: "plant_avocado",
            nameKey: "plant_avocado",
            descriptionKey: "plant_avocado_desc"
        ),
        Plant(
            id: "pineapple",
            scientificName: "Ananas comosus",
            category: .tropical,
            difficulty: .intermediate,
            frostSensitivity: .tropical,
            heatTolerance: .high,
            waterNeeds: .low,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 30, betweenRowsCm: 60),
            daysToHarvest: 365...730,
            soilPreferences: [.sandy, .wellDrained],
            companionPlants: [],
            incompatiblePlants: [],
            indoorSeedWeeks: nil,
            directSowable: true,
            perennial: true,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .moderate,
            plantingDepthCm: 0,
            germinationDays: 0...0,
            optimalTempCelsius: 22...32,
            minSoilTempCelsius: 18,
            imageAssetName: "plant_pineapple",
            nameKey: "plant_pineapple",
            descriptionKey: "plant_pineapple_desc"
        ),
        Plant(
            id: "passionfruit",
            scientificName: "Passiflora edulis",
            category: .tropical,
            difficulty: .intermediate,
            frostSensitivity: .tropical,
            heatTolerance: .high,
            waterNeeds: .moderate,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 300, betweenRowsCm: 400),
            daysToHarvest: 180...365,
            soilPreferences: [.loamy, .wellDrained, .rich],
            companionPlants: [],
            incompatiblePlants: [],
            indoorSeedWeeks: nil,
            directSowable: true,
            perennial: true,
            containerFriendly: false,
            greenhouseSuitable: true,
            humidityPreference: .high,
            plantingDepthCm: 1.0,
            germinationDays: 14...21,
            optimalTempCelsius: 20...30,
            minSoilTempCelsius: 18,
            imageAssetName: "plant_passionfruit",
            nameKey: "plant_passionfruit",
            descriptionKey: "plant_passionfruit_desc"
        ),
        Plant(
            id: "lemongrass",
            scientificName: "Cymbopogon citratus",
            category: .tropical,
            difficulty: .beginner,
            frostSensitivity: .tropical,
            heatTolerance: .extreme,
            waterNeeds: .high,
            sunlight: .fullSun,
            spacing: PlantSpacing(betweenPlantsCm: 60, betweenRowsCm: 90),
            daysToHarvest: 75...120,
            soilPreferences: [.loamy, .rich, .wellDrained],
            companionPlants: [],
            incompatiblePlants: [],
            indoorSeedWeeks: nil,
            directSowable: true,
            perennial: true,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .high,
            plantingDepthCm: 0,
            germinationDays: 7...21,
            optimalTempCelsius: 22...35,
            minSoilTempCelsius: 18,
            imageAssetName: "plant_lemongrass",
            nameKey: "plant_lemongrass",
            descriptionKey: "plant_lemongrass_desc"
        ),
        Plant(
            id: "ginger",
            scientificName: "Zingiber officinale",
            category: .tropical,
            difficulty: .intermediate,
            frostSensitivity: .tropical,
            heatTolerance: .high,
            waterNeeds: .high,
            sunlight: .partialSun,
            spacing: PlantSpacing(betweenPlantsCm: 20, betweenRowsCm: 30),
            daysToHarvest: 240...300,
            soilPreferences: [.loamy, .rich, .wellDrained],
            companionPlants: [],
            incompatiblePlants: [],
            indoorSeedWeeks: nil,
            directSowable: true,
            perennial: true,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .veryHigh,
            plantingDepthCm: 5.0,
            germinationDays: 14...28,
            optimalTempCelsius: 22...30,
            minSoilTempCelsius: 20,
            imageAssetName: "plant_ginger",
            nameKey: "plant_ginger",
            descriptionKey: "plant_ginger_desc"
        ),
        Plant(
            id: "turmeric",
            scientificName: "Curcuma longa",
            category: .tropical,
            difficulty: .intermediate,
            frostSensitivity: .tropical,
            heatTolerance: .high,
            waterNeeds: .high,
            sunlight: .partialSun,
            spacing: PlantSpacing(betweenPlantsCm: 30, betweenRowsCm: 45),
            daysToHarvest: 240...300,
            soilPreferences: [.loamy, .rich, .wellDrained],
            companionPlants: ["ginger"],
            incompatiblePlants: [],
            indoorSeedWeeks: nil,
            directSowable: true,
            perennial: true,
            containerFriendly: true,
            greenhouseSuitable: true,
            humidityPreference: .veryHigh,
            plantingDepthCm: 5.0,
            germinationDays: 21...40,
            optimalTempCelsius: 25...35,
            minSoilTempCelsius: 20,
            imageAssetName: "plant_turmeric",
            nameKey: "plant_turmeric",
            descriptionKey: "plant_turmeric_desc"
        ),
    ]
}
